SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO


CREATE  procedure prc_sel_tblProductRegList
/* ------------------------------------------------------------
   PROCEDURE:    prc_sel_tblProductRegList                         
   
   DESCRIPTION:  Select records FROM table 'tblProductRegistration' for a user                       
					not generated by PBfree
   AUTHOR:       sa 08/09/2004 7:01:32 PM                               
   ------------------------------------------------------------ */
	@UserID                             int 
	AS 
	Select 
		a.RegID,
		a.UserID,
		a.ProductID,
		b.ProductName,
		a.ProductKey,
		a.VendorID,
		c.VendorName,
		a.LicenseNumber,
		a.PurChaseDate,
		a.RegStatus,
		a.Comment,
		a.Update_By,
		a.Enter_Date,
		a.Update_Date,
		b.ProductGraphicLoc
	FROM [tblProductRegistration] a,
		codProducts b,
		codVendors c   	
	WHERE 
		a.ProductID			=	b.ProductID AND
		a.VendorID			=	c.VendorID AND 
		a.[UserID]			=	@UserID
	RETURN @@ERROR

GO
GRANT EXECUTE
	ON [apexsql].[prc_sel_tblProductRegList]
	TO [adrijan.bandu]
GO
GRANT EXECUTE
	ON [apexsql].[prc_sel_tblProductRegList]
	TO [davor.dumeljic]
GO
