SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO


CREATE  procedure prc_sel_SourceCodeList
/* ------------------------------------------------------------
   PROCEDURE:    prc_sel_SourceCodeList                         
   
   DESCRIPTION:  Select records FROM table 'tblProductSourceList'  
		 to manage source links - not generated by PBfree
   AUTHOR:       sa 01/17/2001 7:01:32 PM
		 09/07/2004	                               
   ------------------------------------------------------------ */	
	AS 
	Select 
		a.SourceCodeID,
		a.ProductID,
		b.ProductName,
		b.ProductGraphicLoc,
		a.UrlTitle,
		a.Url,
		a.UrlDescription,
		a.PostedDate
	
	FROM [tblProductSourceCode] a,
		codProducts b
  	
	WHERE 
		a.ProductID			=	b.ProductID 
	RETURN @@ERROR

GO
GRANT EXECUTE
	ON [apexsql].[prc_sel_SourceCodeList]
	TO [adrijan.bandu]
GO
GRANT EXECUTE
	ON [apexsql].[prc_sel_SourceCodeList]
	TO [davor.dumeljic]
GO
