SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER OFF
GO


CREATE  procedure prc_sel_SourceListForUser
/* ------------------------------------------------------------
   PROCEDURE:    prc_sel_SourceListForUser                         
   
   DESCRIPTION:  Select source links FROM table 'tblProductSourceList'
		 based on Product registrations in 'tblProductRegistration'
		 For a customer(User)
		 - not generated by PBfree
   AUTHOR:       sa 01/17/2002 6:01:32 PM
		 09/07/2004	                               
   ------------------------------------------------------------ */	
	@UserID		Int
	AS 
	(Select 
		b.SourceCodeID,
		b.ProductID,
		c.ProductName,
		c.ProductGraphicLoc,
		b.UrlTitle,
		b.Url,
		b.UrlDescription,
		b.PostedDate,
		'y' as lnk
	FROM     
		[tblProductSourceCode] b, 
		codProducts c
  	
	WHERE 
		b.ProductID	=	c.ProductID and
		b.ProductID in (Select a.ProductID from tblProductRegistration a
		where a.UserID = @UserID AND (a.RegStatus = 1)) 
	
	
Union
	Select 
		b.SourceCodeID,
		b.ProductID,
		c.ProductName,
		c.ProductGraphicLoc,
		b.UrlTitle,
		b.Url,
		b.UrlDescription,
		b.PostedDate,
		'n' as lnk
	FROM     
		[tblProductSourceCode] b, 
		codProducts c
  	
	WHERE 
		b.ProductID	=	c.ProductID and
		b.ProductID Not in (Select a.ProductID from tblProductRegistration a
		where a.UserID = @UserID AND (a.RegStatus = 1)))
	Order by c.ProductName	
		 
	RETURN @@ERROR

GO
GRANT EXECUTE
	ON [apexsql].[prc_sel_SourceListForUser]
	TO [adrijan.bandu]
GO
GRANT EXECUTE
	ON [apexsql].[prc_sel_SourceListForUser]
	TO [davor.dumeljic]
GO
