SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [apexsql].[sin] (
		[id]     [int] IDENTITY(1, 1) NOT NULL,
		[nd]     [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [apexsql].[sin] SET (LOCK_ESCALATION = TABLE)
GO
