SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ICE_Free_Domains] (
		[ID]         [int] IDENTITY(1, 1) NOT NULL,
		[Domain]     [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ICE_Free_Domains]
	ADD
	CONSTRAINT [PK__ICE_Free__3214EC273F6AF381]
	PRIMARY KEY
	CLUSTERED
	([ID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ICE_Free_Domains] SET (LOCK_ESCALATION = TABLE)
GO
