SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Email-Temp] (
		[ID]        [int] IDENTITY(1, 1) NOT NULL,
		[Email]     [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Email-Temp] SET (LOCK_ESCALATION = TABLE)
GO
